### ISSUE TITLE
 AttributeError: 'RangeIndex' object has no attribute 'get_values'

### ISSUE THREAD

**Issue by farrukh846** [NaegleLab/OpenEnsembles#15]
Hello,

the error raised when i execute this line:

coMat = c.co_occurrence_matrix()

Error raised:

AttributeError: 'RangeIndex' object has no attribute 'get_values'

the error occured which mentioned in the title, please lets fix this issue.

**Comment by knaegle** [comment]
This issue should be fixed now in the Py3 version of OpenEnsembles we are just about to release, we are not seeing this issue in testing at this point.
