### ISSUE TITLE
Saving a cluster ensemble model

### ISSUE THREAD

**Issue by Kosisochi** [NaegleLab/OpenEnsembles#17]
Is it possible to save the final clustering model derived from mixture_model and then reload that model when you want to find the cluster a new data instance belongs to ?

I didnt see anything in relation to this is in the documentation. 

Any tips?

**Comment by Kosisochi** [comment]
So i have saved the model by pickling it. 
When using a single kmeans, i can do model.predict(new_data_instance)
Is there something similar in openensembles::

**Comment by srcrowl** [comment]
Pickling the openEnsembles object would be the quickest way to save all information regarding the model and results. However, openEnsembles is built entirely for unsupervised learning (clustering) and not for supervised learning approaches like the kmeans predict function. If you are wanting to perform classification of new data, this package is likely not your best option.

**Comment by Kosisochi** [comment]
> Pickling the openEnsembles object would be the quickest way to save all information regarding the model and results. However, openEnsembles is built entirely for unsupervised learning (clustering) and not for supervised learning approaches like the kmeans predict function. If you are wanting to perform classification of new data, this package is likely not your best option
