### ISSUE TITLE
"ImportError: No module named transforms"

### ISSUE THREAD

**Issue by MaxAlex** [NaegleLab/OpenEnsembles#2]
After installing from either pip or the Github repository copy, attempting to import the OpenEnsembles module raises an ImportError:

Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import openensembles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/openensembles/__init__.py", line 1, in <module>
    from openensembles.openensembles import *
  File "/usr/local/lib/python2.7/dist-packages/openensembles/openensembles.py", line 25, in <module>
    import openensembles.transforms as tx
ImportError: No module named transforms
>>>

From looking into the code, it seems like there's a circular import through openensembles/__init__.py : to import openensembles.transforms, Python must first import openensembles/__init__.py, and this attempts to import everything under openensembles, including openensembles.transforms.

**Comment by shawnanastasio** [comment]
Thanks for the report.

This issue only occurs on Python 2 which OpenEnsembles does not support. Installing via pip3 and running with Python 3 should resolve this issue for you.

I have also updated the readme to reflect this requirement.
